# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

matrix:
  include:
  - r: devel
    env: _R_CHECK_LENGTH_1_LOGIC2_=true
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
    before_deploy:
    - R CMD INSTALL .
    deploy:	
      provider: pages	
      skip-cleanup: true	
      github-token: $GITHUB_PAT	
      keep-history: true	
      on:	
        branch: master
      target_branch: gh-pages
  - r: release
    pandoc: false
    env: PANDOC='none'
  - r: oldrel
  - r: 3.3
  - r: 3.4
  - r: 3.5
  - r: 3.6


env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=TRUE
