# adapted from https://github.com/actions/stale
name: 'Close stale issues and PR'
on:
  schedule:
    - cron: '11 1 * * 6'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-issue-message: 'This issue is stale because it has been open 365 days with no activity. Remove stale label or comment or this will be closed in 7 days.'
          stale-pr-message: 'This PR is stale because it has been open 45 days with no activity. Remove stale label or comment or this will be closed in 10 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 7 days with no activity.'
          exempt-issue-labels: 'blocked,must,should,keep'
          days-before-stale: 365
          days-before-close: 7
          days-before-pr-close: -1

